# Generated by Django 4.0.4 on 2022-05-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar1',
            name='cumpleanos',
        ),
        migrations.RemoveField(
            model_name='familiar2',
            name='cumpleanos',
        ),
        migrations.RemoveField(
            model_name='familiar3',
            name='cumpleanos',
        ),
        migrations.AlterField(
            model_name='familiar1',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='familiar2',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='familiar3',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
